# Generated by Django 5.2.1 on 2025-05-28 20:44

import Inicio.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
                ('objects', Inicio.managers.UsuarioManager()),
            ],
        ),
    ]
