# Generated by Django 5.2.1 on 2025-05-28 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0003_centro_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='tipo',
            field=models.CharField(choices=[('FERT', 'FERT - Producto terminado'), ('ROH', 'ROH - Materia prima'), ('HALB', 'HALB - Producto semi-terminado'), ('SERV', 'SERV - Servicio')], max_length=10),
        ),
    ]
