# Generated by Django 5.2.1 on 2025-05-28 22:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0004_alter_material_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponenteMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usado_en', to='Inicio.material')),
                ('material_padre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes', to='Inicio.material')),
            ],
            options={
                'verbose_name': 'Componente de Material',
                'verbose_name_plural': 'Componentes de Material',
            },
        ),
    ]
