# Generated by Django 5.2.1 on 2025-06-18 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0005_componentematerial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='centro',
        ),
        migrations.RemoveField(
            model_name='componentematerial',
            name='componente',
        ),
        migrations.RemoveField(
            model_name='componentematerial',
            name='material_padre',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('materiales', 'Materiales'), ('planificacion', 'Planificacion'), ('aprobador', 'Aprobador'), ('compras', 'Compras'), ('almacen', 'Almacen')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Centro',
        ),
        migrations.DeleteModel(
            name='ComponenteMaterial',
        ),
        migrations.DeleteModel(
            name='Material',
        ),
    ]
