# Generated by Django 5.2.1 on 2025-06-19 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0007_sede_almacen'),
    ]

    operations = [
        migrations.CreateModel(
            name='FERT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=8, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('unidad_base', models.CharField(default='KG', max_length=10)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales_fert', to='Inicio.sede')),
            ],
        ),
        migrations.CreateModel(
            name='ROH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=8, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('unidad_base', models.CharField(default='KG', max_length=10)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales_roh', to='Inicio.sede')),
            ],
        ),
        migrations.CreateModel(
            name='BOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes', to='Inicio.fert')),
                ('roh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usado_en', to='Inicio.roh')),
            ],
            options={
                'unique_together': {('fert', 'roh')},
            },
        ),
    ]
