# Generated by Django 5.2.1 on 2025-06-19 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0008_fert_roh_bom'),
    ]

    operations = [
        migrations.AddField(
            model_name='roh',
            name='almacen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiales_roh', to='Inicio.almacen'),
        ),
    ]
