# Generated by Django 5.2.1 on 2025-06-19 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0009_roh_almacen'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_fert', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_fert_con_extra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo_insumos', models.DecimalField(decimal_places=2, max_digits=12)),
                ('costo_total_estimado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes', to='Inicio.fert')),
            ],
        ),
        migrations.CreateModel(
            name='PlanProduccionDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField()),
                ('año', models.IntegerField()),
                ('cantidad_en_mes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='Inicio.planproduccion')),
            ],
        ),
        migrations.CreateModel(
            name='PlanProduccionInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_requerida', models.DecimalField(decimal_places=2, max_digits=12)),
                ('costo_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumos', to='Inicio.planproduccion')),
                ('roh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inicio.roh')),
            ],
        ),
    ]
