# Generated by Django 5.2.1 on 2025-06-19 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0010_planproduccion_planproducciondetalle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bom',
            name='cantidad',
            field=models.IntegerField(),
        ),
    ]
