# Generated by Django 5.2.1 on 2025-06-19 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0011_alter_bom_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planproduccion',
            name='cantidad_fert',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='planproduccion',
            name='cantidad_fert_con_extra',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='planproducciondetalle',
            name='cantidad_en_mes',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='planproduccioninsumo',
            name='cantidad_requerida',
            field=models.IntegerField(),
        ),
    ]
