# Generated by Django 5.2.1 on 2025-06-19 03:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0013_fert_almacen'),
    ]

    operations = [
        migrations.CreateModel(
            name='SOLPED',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('ordenado', 'Ordenado')], default='pendiente', max_length=20)),
                ('total_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solpeds', to='Inicio.sede')),
                ('plan_produccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solpeds', to='Inicio.planproduccion')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solpeds', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SOLPEDItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('unidad', models.CharField(max_length=10)),
                ('costo_estimado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inicio.roh')),
                ('plan_insumo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solped_items', to='Inicio.planproduccioninsumo')),
                ('solped', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Inicio.solped')),
            ],
        ),
    ]
