# Generated by Django 5.2.1 on 2025-06-19 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0014_solped_solpeditem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('ruc', models.CharField(help_text='Número de RUC o identificación fiscal', max_length=20, unique=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contacto', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.BooleanField(default=True, help_text='Activo o inactivo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
