# Generated by Django 5.2.1 on 2025-06-19 04:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0015_proveedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='OCItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('cantidad', models.IntegerField()),
                ('unidad', models.CharField(max_length=10)),
                ('costo_estimado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oc_items', to='Inicio.proveedor')),
                ('solped_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oc_items', to='Inicio.solpeditem')),
            ],
        ),
        migrations.CreateModel(
            name='OCEntregaProgramada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrega', models.DateField()),
                ('cantidad', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas_programadas', to='Inicio.ocitem')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('total_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_compra', to=settings.AUTH_USER_MODEL)),
                ('solped', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_compra', to='Inicio.solped')),
            ],
        ),
        migrations.AddField(
            model_name='ocitem',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Inicio.ordencompra'),
        ),
    ]
