# Generated by Django 5.2.1 on 2025-06-19 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0016_ocitem_ocentregaprogramada_ordencompra_ocitem_orden'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntradaMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='Inicio.almacen')),
                ('orden_compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inicio.ordencompra')),
            ],
        ),
        migrations.CreateModel(
            name='EntradaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inicio.roh')),
                ('oc_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inicio.ocitem')),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Inicio.entradamaterial')),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cantidad', models.IntegerField(help_text='Positivo: entrada, Negativo: salida')),
                ('motivo', models.CharField(help_text="Ejemplo: 'Entrada OC', 'Consumo Producción', 'Ajuste'", max_length=200)),
                ('referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='Inicio.almacen')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inicio.roh')),
            ],
        ),
    ]
