# Generated by Django 5.2.1 on 2025-06-19 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0017_entradamaterial_entradaitem_movimientostock'),
    ]

    operations = [
        migrations.AddField(
            model_name='almacen',
            name='cantidad',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
