# Generated by Django 5.2.1 on 2025-07-03 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0018_almacen_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planproduccion',
            name='costo_insumos',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='planproduccion',
            name='costo_total_estimado',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='planproduccion',
            name='fert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inicio.fert'),
        ),
        migrations.CreateModel(
            name='PlanCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('produccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_compra', to='Inicio.planproduccion')),
            ],
        ),
        migrations.CreateModel(
            name='PlanCompraItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_comprar', models.IntegerField()),
                ('costo_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Inicio.plancompra')),
                ('roh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inicio.roh')),
            ],
        ),
        migrations.AlterField(
            model_name='solpeditem',
            name='plan_insumo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solped_items', to='Inicio.plancompraitem'),
        ),
        migrations.CreateModel(
            name='PlanVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_total', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_venta', to='Inicio.fert')),
            ],
        ),
        migrations.AddField(
            model_name='planproduccion',
            name='venta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='planes_produccion', to='Inicio.planventa'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PlanVentaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField()),
                ('año', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='Inicio.planventa')),
            ],
        ),
        migrations.DeleteModel(
            name='PlanProduccionInsumo',
        ),
    ]
